
job:
  runModel:
    parameters:
      expected_base_rate: 1
      expected_employee_cost_change: 0.0

    inputs:
      net_interest_margin: "outputs/net_interest_margin.csv"
      average_interest_earning_assets: "inputs/average_interest_earning_assets.csv"

    outputs:
      net_interest_income: "outputs/net_interest_income.csv"
